# Generated by Django 3.2.18 on 2023-06-21 11:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GameList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pos_index', models.IntegerField(unique=True, verbose_name='Номер')),
                ('game_field', models.CharField(blank=True, default='', max_length=100, verbose_name='поле игры')),
                ('player_figure', models.CharField(blank=True, default='', max_length=100, verbose_name='игровая фигура')),
                ('winner', models.CharField(blank=True, default='', max_length=100, verbose_name='победитель')),
                ('game_date', models.DateTimeField(blank=True, null=True, verbose_name='дата игры')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
    ]
