# Generated by Django 3.2.18 on 2023-06-22 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tictactoe', '0003_alter_gamelist_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamelist',
            name='pos_index',
        ),
    ]
