# Generated by Django 3.2.18 on 2023-06-22 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tictactoe', '0004_remove_gamelist_pos_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamelist',
            name='user_pk',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
