# Generated by Django 3.2.18 on 2023-06-23 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tictactoe', '0005_gamelist_user_pk'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamelist',
            name='winner_cells',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='ячейки победы'),
        ),
    ]
