# Generated by Django 3.2.18 on 2023-06-24 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tictactoe', '0006_gamelist_winner_cells'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamelist',
            name='game_field',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='поле игры'),
        ),
        migrations.AlterField(
            model_name='gamelist',
            name='winner_cells',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='ячейки победы'),
        ),
    ]
