# Generated by Django 3.2.18 on 2023-06-25 11:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tictactoe', '0007_auto_20230624_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamelist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gamelist', to=settings.AUTH_USER_MODEL),
        ),
    ]
